# Generated by Django 3.2.7 on 2021-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_mobile_no', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
                ('Emp_address', models.TextField(max_length=100)),
            ],
        ),
    ]
