# Generated by Django 3.2.7 on 2021-10-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employe_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_tite', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Emp_address',
            new_name='emp_address',
        ),
        migrations.AddField(
            model_name='employee',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employe_App.position'),
        ),
    ]
