# Generated by Django 3.2.7 on 2021-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe_App', '0002_auto_20211018_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_dob',
            field=models.DateField(null=True),
        ),
    ]
