# Generated by Django 3.2.7 on 2021-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe_App', '0003_employee_emp_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
